config/routes.rb
Rails.application.routes.draw do

  require "sidekiq/web"
  mount Sidekiq::Web => "/sidekiq"

  root "articles#index"
    resources :articles do
      resources :comments
    end
  # resources:articles
  # get "/articles", to: "articles#index"
  # # get "/price",to:"price#show"
  # get "/articles/:id",to: "articles#show"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments, dependent: :destroy
  include Visible
  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10 }

  
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  before_save { self.email = email.downcase}
  include Visible
  validates :status, inclusion: { in: VALID_STATUSES }
  validates :email, email: true

  # def archived?
  #   status == 'archived'
  # end

end

app/models/concerns/visible.rb
module Visible
  extend ActiveSupport::Concern
  VALID_STATUSES = ['public', 'private', 'archived']
  included do
    validates :status, inclusion: { in: VALID_STATUSES }
  end
  class_methods do
    def public_count
      where(status: 'public').count
    end
  end

  def archived?
    status == 'archived'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  require 'rubygems'
  require 'twilio-ruby'


  # for the user simple authentication
  http_basic_authenticate_with name: "dhh", password: "secret", except: [:index, :show]

  def index
    @article=Article.all
  end
  def show
    @article=Article.find(params[:id])
  end
  def new
    @article=Article.new
  end

  def create
    @article= Article.new(article_param)
    if @article.save
      MakeMsgJob.perform_later(@article)
      redirect_to @article
    else
      render :new ,status: :unprocessable_entity
    end
  end

  def edit
    @article=Article.find(params[:id])
  end

  def update
     @article=Article.find(params[:id])
     if @article.update(article_param)
      redirect_to @article #show will class /article/:id
    else
      render :edit,status: :unprocessable_entity
    end
  end

 def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to root_path, status: :see_other
  end



  private 
  def article_param
    params.require(:article).permit(:title,:body,:status)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  http_basic_authenticate_with name: "dhh", password: "secret", only: :destroy
	def error
	end
	def show
		@comment=Comment.find(params[:id])
	end
	def create
		@article =Article.find(params[:article_id])
		@comment =@article.comments.new(comment_params)
		if @comment.save
			RegistrationJob.perform_later (@comment)
			redirect_to article_path(@article)
		else
			redirect_to article_path(@article)
		end
	end

	def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article), status: 303
  end


	private
		def comment_params
			params.require(:comment).permit(:commenter,:body,:status,:email)
		end
end

app/controllers/price_controller.rb
class PriceController < ApplicationController
	def show
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/price_helper.rb
module PriceHelper
end

app/views/articles/_comment.html.erb
<% article.comments.each do |comment| %>
    <% unless comment.archived? %>
    <p>
      <strong>Commenter:</strong>
      <%= comment.commenter %>
    </p>
    <p>
      <strong>Email:</strong>
      <%= comment.email %>
    </p>
    <p>
      <strong>Comment:</strong>
      <%= comment.body %>
    </p>
    <p>
    <%= link_to "Destroy Comment", [comment.article, comment], data: {
                turbo_method: :delete,
                turbo_confirm: "Are you sure?"
              } %>
    </p>
  <% end %>
<% end %>

app/views/articles/_form.html.erb
<%= form_with model: article do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% article.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %><br>
    <% article.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div>
  <%= form.label :status %><br>
  <%= form.select :status, ['public', 'private', 'archived'], selected: 'public' %>
</div>


  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render "form", article: @article %>

app/views/articles/index.html.erb
<h1>Articles</h1>

Our blog has <%= Article.public_count %> articles and counting!

<ul>
  <% @article.each do |article| %>
    <% unless article.archived? %>
      <li>
        <%= link_to article.title, article %> <!-- show action will call and pass the article id-->
      </li>
    <% end %>
  <% end %>
</ul>

<%= link_to "New Article", new_article_path %> <!-- call the new action -->

app/views/articles/new.html.erb
<!-- <h1>New Article<h1>

<%= form_with model: @article do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% @article.errors.full_messages_for(:title).each do |message| %>
    <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
    <% @article.errors.full_messages_for(:body).each do |message| %>
    <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>
 -->
 <h1>New Article</h1>

<%= render "form", article: @article %>

app/views/articles/show.html.erb
<%= link_to image_tag("ruby.png"), articles_path%>
<h1><%= @article.title %></h1>

<p><%= @article.body %></p>
<ul>
   <li><%= link_to "Edit", edit_article_path(@article) %></li>
   <li><%= link_to "Destroy", article_path(@article), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li>



<!--show comments-->
<h2>Comments</h2>
<%= render "comment", article:@article %>

<h2>Add a comment:</h2>
<%= render "comments/form",article:@article%>

app/views/comments/_form.html.erb
<%= form_with model: [ article, article.comments.build ] do |form| %>

  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :email %><br>
    <%= form.text_field :email %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
  <%= form.label :status %><br>
  <%= form.select :status, ['public', 'private', 'archived'], selected: 'public' %>
</p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/comments/show.html.erb
<h1><%= @article.title %></h1>

<p><%= @article.body %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/price/show.html.erb
<h1>Price</h1>